### ISSUE TITLE
add Ethernet chip

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Kasli-SOC#12]
add the Marvell Ethernet chip as on ZC706 devkit. It is in CERN lib. It was also used in MARBLE AMC FMC design. It is connected to SoC using RGMII

**Comment by gkasprow** [comment]
copy pinout from  ZC706

**Comment by gkasprow** [comment]
and add connector with magnetics.

**Comment by gkasprow** [comment]
Please use verified schematic from Marble board
https://github.com/BerkeleyLab/Marble

**Comment by filipswit** [comment]
Added. 
BTW It looks like in Marble is a small bug. VDDO_SEL should be tied low for 2.5V operaion.
