### ISSUE TITLE
route CK_FPGAIO to CC pins

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Kasli-SOC#15]

**Comment by gkasprow** [comment]
the same with
Helper_DCXO

**Comment by gkasprow** [comment]
the same with CKIN SMA

**Comment by gkasprow** [comment]
it's better to use LVDS version for OSC2. @sbourdeauducq do we need yet another oscillator for PL?

**Comment by sbourdeauducq** [comment]
What is the RTIO clock source and can it be entirely started from the PS in all configurations?

**Comment by gkasprow** [comment]
do you mean DRTIO? what do you mean 

> entirely started from the PS in all configurations

define: "entirely", "from the PS", "all configurations"

**Comment by sbourdeauducq** [comment]
No, regular RTIO also needs a clock. On Kasli it is provided by the Si5324 even when DRTIO is not used.

**Comment by filipswit** [comment]
So, additional OSC2 is not needed, right?
