### ISSUE TITLE
use E24 RC

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Kasli-SOC#17]
Try to use E24-series RC: DDR termination can be 39R, 
LDO and SMPS FB resistors can be calculated out of E24 using [this tool](http://mustcalculate.com/electronics/automaticresistivevoltagedivider.php?vin=2.5&vout=0.8&eser=E24&rmin=1k&rmax=100k)
this limits the BOM count

**Comment by filipswit** [comment]
Ok.
