### ISSUE TITLE
Change J24 to PL UART

### ISSUE THREAD

**Issue by kaolpr** [sinara-hw/Kasli-SOC#19]
If there is no serious reason to have J24 maybe FTDI D-port could be connected to SoC PL? It would enable easy use of logic analyzers like Litescope or Microscope.

**Comment by filipswit** [comment]
Added Rx/Tx from FTDI to SocPL is it fine for you?

**Comment by kaolpr** [comment]
Did you push it to the repo? Which port of the FTDI?
