### ISSUE TITLE
Memory bus width

### ISSUE THREAD

**Issue by dhslichter** [sinara-hw/Kasli-SOC#21]
Previous issues with DMA slowness on Kasli (https://github.com/m-labs/artiq/issues/946) suggest that it would be helpful to make the memory bus wider.  If Kasli-SOC is to be a higher-performance sibling of Kasli, it seems we should think about a wider memory bus (more like KC705)?

**Comment by filipswit** [comment]
Not sure what we can do with it. On KC705 bus is x64. In Kasli-SOC we connect RAM to PS only, so we have x32.
