### ISSUE TITLE
speed grade

### ISSUE THREAD

**Issue by sbourdeauducq** [sinara-hw/Kasli-SOC#33]
The [initial proposal](https://github.com/sinara-hw/Kasli-SOC/issues/1) called for the "fastest speed grade", yet the schematics has speed grade 2.

There are quite some difference in PS performance between the grades. Can we get speed grade 3?

![image](https://user-images.githubusercontent.com/720864/104564410-d50d7480-5685-11eb-9801-0f36808d6b98.png)

**Comment by gkasprow** [comment]
I think you can specify which SG you want during ordering the board.

**Comment by sbourdeauducq** [comment]
Certainly, but we're not going to support more than one speed grade in ARTIQ, and that should be speed grade 3.

**Comment by filipswit** [comment]
I've replaced Zynq symbol to: XC7Z030-3FFG676E
