### ISSUE TITLE
Rear power connector

### ISSUE THREAD

**Issue by kaolpr** [sinara-hw/Kasli-SOC#49]
Is the rear power connector purposely different from the one on Kasli v2.0?

**Comment by filipswit** [comment]
Well, I marked mounted,  same as on Kasli 2.0.1- J20. Should it be DC jack - J26?
![image](https://user-images.githubusercontent.com/24258965/108764580-14679480-7553-11eb-9bf5-652cb596fdf9.png)

**Comment by kaolpr** [comment]
That's ok, my mistake.
