### ISSUE TITLE
Ethernet PHY reset may need to be asserted during power up

### ISSUE THREAD

**Issue by sbourdeauducq** [sinara-hw/Kasli-SOC#53]
The Zynq cannot do it. Not sure if another reset after power-up is sufficient. Currently (without any reset) Ethernet communications work but not MDIO.
![image](https://user-images.githubusercontent.com/720864/120049569-fa0aee80-c04c-11eb-9e03-c620f178e906.png)

**Comment by sbourdeauducq** [comment]
On the ZC706 (with a similar but not identical PHY) they have a gate to generate the power-up reset, so this could be important.
![image](https://user-images.githubusercontent.com/720864/120049895-10fe1080-c04e-11eb-834a-f8c60442af2a.png)

**Comment by sbourdeauducq** [comment]
corresponding firmware issue: https://git.m-labs.hk/M-Labs/zynq-rs/issues/78

**Comment by sbourdeauducq** [comment]
Having or not having a power-up reset does not seem to make a difference, PHY works in both cases.
Tested by @TopQuark12

**Comment by TopQuark12** [comment]
Current hardware configuration works fine as is, holding rst down during power on does not affect the behavior of the phy chip in observation. Would be helpful if the schematics indicate the PHY MDIO address is 0.

**Comment by gkasprow** [comment]
added note
