### ISSUE TITLE
Typo: incorrect MPN and description for Zynq-7000

### ISSUE THREAD

**Issue by HarryMakes** [sinara-hw/Kasli-SOC#60]
Hi, I'd like to report a minor discrepancy. I found that the BOM shows a minor typo on the row for the Zynq-7000 chip:

![image](https://user-images.githubusercontent.com/66358631/131955065-594aa36d-67e8-4597-99cd-d6d5ba058e4b.png)

The correct P/N is XC7Z030-3FFG67**6**E, but the "manufacturer part number" shows "XC7Z030-3FFG67E" (with only one '6') instead.

The "description" too is different, which seems to refer to the old speed grade (2) and/or temperature range (I).

As shown on the Altium PCBDOC (using the [online viewer](https://www.altium.com/viewer/)), the typo also exists on the design file. Additionally the "device" parameter matches the outdated "description", but this doesn't affect the BOM.

![image](https://user-images.githubusercontent.com/66358631/131955521-47593e32-7c09-4eae-a1e8-ad3e75d2ef61.png)

Other parameters such as "part number" are mostly correct. Thank you.

**Comment by filipswit** [comment]
Fixed in v1.0.1
