### ISSUE TITLE
IC40 label overlaps the copper pad

### ISSUE THREAD

**Issue by HarryMakes** [sinara-hw/Kasli-SOC#62]
We found that on the bottom layer, the label for IC40 on the bottom layer overlay is overlapping the copper pad for the heatsink.

![image](https://user-images.githubusercontent.com/66358631/146337094-7b1b1e1e-6e62-43ab-bf1c-0017533a7dad.png)

**Comment by gkasprow** [comment]
It looks like there is a rule missing or disabled

**Comment by HarryMakes** [comment]
CC @sbourdeauducq

**Comment by gkasprow** [comment]
fixed
