### ISSUE TITLE
v1.1

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Kasli-SOC#65]
@gkasprow @sbourdeauducq @hartytp and whoever else is interested

I'm not fully aware of what the current state of Kasli-SoC is beyond what I can tell from the repositories. We are being asked regularly what the status and are mostly recommending that people wait or get involved actively. Two things:

* Is Kasli-SoC being used somewhere actively and more or less continuously or is everybody waiting for somebody else to go through the v1.0 hardware pain phase?
* Does it make sense to address the current HW issues in a v1.1 now (or is it good enough/not enough issues to bother)?

**Comment by hartytp** [comment]
Been trying to get our hands on one for a very very long time, but the ship date from CTI keeps slipping...

**Comment by gkasprow** [comment]
Yes, the lead time of many ICs is a serious issue. These days I don't even start a new project before making sure all ICs arrived.

**Comment by jordens** [comment]
@pkozakiewicz apparently has the parts and could make some, waiting for a decision regarding v1.0 vs v1.1 boards.
We are in the queue for a couple but happy to reduce if someone wants to forge ahead.

**Comment by gkasprow** [comment]
I'd suggest fixing only minor issues for the moment. I can assign a dedicated engineer in 6 weeks who would implement all changes.

**Comment by dhslichter** [comment]
@jordens for those interested in a Zynq core device with Sinara hardware on a shorter timescale, one option is to use ZC706 as a DRTIO root node and then connect to satellite Kasli(s) in Sinara crate(s) via optical fiber. NIST has funded DRTIO master/satellite for ZC706 and KC705, and we are debugging ZC706 master/Kasli satellite on the magtrap setup at present.

**Comment by jordens** [comment]
I am aware but not interested in the ZC706. This is about Kasli-SoC.

**Comment by hartytp** [comment]
@cjbe will know the details better than me, but IIRC we ordered a pretty large batch from CTI a while ago and don't plan to order more until testing has been done. CTI are still having stock issues (even if TS have some).

**Comment by sbourdeauducq** [comment]
No major issues in v1.0 from what I can tell, only what I reported.

**Comment by pkozakiewicz** [comment]
@jordens I have one board left that was produced for our internal use. We have finished our work with it. Would you need it for hands-on experience before confirming production of the current release?

**Comment by pkozakiewicz** [comment]
What is the final decision on this topic? Shall we wait for v1.1 or produce v1.0 immediately?

**Comment by gkasprow** [comment]
@pkozakiewicz Produce v1.0 but make R33=2k2

**Comment by pkozakiewicz** [comment]
@gkasprow @jordens @sbourdeauducq @hartytp Good, we are starting production.

**Comment by gkasprow** [comment]
fixed in v1.0.1
