### ISSUE TITLE
revision ID and variant ID

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Kasli-SOC#70]
@filipswit please add REV_ID signals as in Stabilizer/Phaser/Thermostat
set revID = 1 because we have  1.1 PCB
make rev ID 4 bits
you can use any FPGA pins, could be in different banks
place the variant ID close to the I2C expanders.
The firmware must know which expanders are assembled. One can theoretically detect them looking at their address but having a dedicated pin is easier.
Here is how revision/variant ID is implemented in Phaser 
![image](https://user-images.githubusercontent.com/4325054/203554688-2e3a6dc9-e0b3-431f-82ec-601d94944068.png)

**Comment by filipswit** [comment]
Added:
![image](https://user-images.githubusercontent.com/24258965/203595450-c06d0347-7978-4bde-9d0c-7436f8c5558a.png)
